# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-23 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0004_auto_20180423_1701'),
    ]

    operations = [
        migrations.DeleteModel(
            name='myList',
        ),
        migrations.RemoveField(
            model_name='wish',
            name='uploaded_by_id',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Wish',
        ),
    ]
