# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-23 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0007_auto_20180423_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='item',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
