# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-23 20:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0009_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='guest',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='first_app.Guest'),
            preserve_default=False,
        ),
    ]
